// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/size12/gophkeeper/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// ClientConn is an autogenerated mock type for the ClientConn type
type ClientConn struct {
	mock.Mock
}

// CreateRecord provides a mock function with given fields: token, record
func (_m *ClientConn) CreateRecord(token entity.AuthToken, record entity.Record) error {
	ret := _m.Called(token, record)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.AuthToken, entity.Record) error); ok {
		r0 = rf(token, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRecord provides a mock function with given fields: token, recordID
func (_m *ClientConn) DeleteRecord(token entity.AuthToken, recordID string) error {
	ret := _m.Called(token, recordID)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.AuthToken, string) error); ok {
		r0 = rf(token, recordID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRecord provides a mock function with given fields: token, recordID
func (_m *ClientConn) GetRecord(token entity.AuthToken, recordID string) (entity.Record, error) {
	ret := _m.Called(token, recordID)

	var r0 entity.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.AuthToken, string) (entity.Record, error)); ok {
		return rf(token, recordID)
	}
	if rf, ok := ret.Get(0).(func(entity.AuthToken, string) entity.Record); ok {
		r0 = rf(token, recordID)
	} else {
		r0 = ret.Get(0).(entity.Record)
	}

	if rf, ok := ret.Get(1).(func(entity.AuthToken, string) error); ok {
		r1 = rf(token, recordID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecordsInfo provides a mock function with given fields: token
func (_m *ClientConn) GetRecordsInfo(token entity.AuthToken) ([]entity.Record, error) {
	ret := _m.Called(token)

	var r0 []entity.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.AuthToken) ([]entity.Record, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(entity.AuthToken) []entity.Record); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(entity.AuthToken) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: credentials
func (_m *ClientConn) Login(credentials entity.UserCredentials) (string, error) {
	ret := _m.Called(credentials)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.UserCredentials) (string, error)); ok {
		return rf(credentials)
	}
	if rf, ok := ret.Get(0).(func(entity.UserCredentials) string); ok {
		r0 = rf(credentials)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entity.UserCredentials) error); ok {
		r1 = rf(credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: credentials
func (_m *ClientConn) Register(credentials entity.UserCredentials) (string, error) {
	ret := _m.Called(credentials)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.UserCredentials) (string, error)); ok {
		return rf(credentials)
	}
	if rf, ok := ret.Get(0).(func(entity.UserCredentials) string); ok {
		r0 = rf(credentials)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entity.UserCredentials) error); ok {
		r1 = rf(credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClientConn interface {
	mock.TestingT
	Cleanup(func())
}

// NewClientConn creates a new instance of ClientConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientConn(t mockConstructorTestingTNewClientConn) *ClientConn {
	mock := &ClientConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
